# Generated by Django 2.1.4 on 2019-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190112_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
