# Generated by Django 2.1.4 on 2019-01-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_auto_20190120_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('DATAS', '数据'), ('NEWS', '新闻'), ('OTHERS', '其他')], default='OTHERS', max_length=10),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
