# Generated by Django 2.1.4 on 2018-12-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='stock',
        ),
        migrations.AddField(
            model_name='industry',
            name='stock',
            field=models.ManyToManyField(to='stock_analyze.Stock'),
        ),
    ]
