# Generated by Django 2.1.4 on 2018-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0002_auto_20181229_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
