# Generated by Django 2.1.4 on 2018-12-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0003_auto_20181229_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='stock',
            new_name='stocks',
        ),
    ]
