# Generated by Django 2.1.4 on 2019-01-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0004_auto_20181229_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='order',
            field=models.SmallIntegerField(default=100),
        ),
    ]
